OnlineBusTicketManagement/OnlineBusTicketManagement/Controllers/RouteController.cs
using OBTM.Core.Models;
using OBTM.DataAccess;
using OBTM.Service;
using OnlineBusTicketManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineBusTicketManagement.Controllers
{
    [AuthorizeWithSession]
    public class RouteController : Controller
    {
        RouteService rs = new RouteService();
        RoutePointsService rps = new RoutePointsService();
        OperatorRouteMapService orm = new OperatorRouteMapService();
        BusOperatorService bos = new BusOperatorService();
        LocationsService ls = new LocationsService();

        // GET: Route
        OBTMDbContext context = new OBTMDbContext();

        string successMessage = "Saved successfully!";
        string failureMessage = "Error occurred! Please Try again.";
        Response<int> response;
        public ActionResult Index()
        {

            //Route r = new Route {
            //    RouteName = "D-K-J"
            //};
            //rs.Save(r);
            //OperatorRouteMap op = new OperatorRouteMap
            //{
            //    BusOperatorId = 1,
            //    RouteId= r.Id
            //};
            //orm.Save(op);
            //rps.Save(new RoutePoints() { RouteId = 1, LocationId = 1, SequenceId=1});
            //rps.Save(new RoutePoints() { RouteId = 1, LocationId = 2 ,SequenceId=2});
            //rps.Save(new RoutePoints() { RouteId = 1, LocationId = 3 , SequenceId=3});

            ViewBag.BusOperatorList = new SelectList(context.BusOperators, "Id", "Name");
            ViewBag.LocationList = new SelectList(context.Locations, "Id", "Location");
            ViewBag.ExistingRouteList = new SelectList(context.Routes, "Id", "RouteName");
            var preBusList = bos.GetAll();
            List<BusOperator> postBusList = new List<BusOperator>();
            foreach (var item in preBusList)
            {
                if (item.IsDeleted==null || item.IsDeleted==false)
                {
                    postBusList.Add(item);
                }
                
            }
            return View(postBusList);
            

        }
        public ActionResult SaveRoute(Route r)
        {
            RouteService rs = new RouteService();
            rs.Save(r);
            return View("Index");
        }
        public ActionResult Delete(int id)
        {
            orm.DeleteSingleRouteForBus(id);
            return RedirectToAction("Index");
        }
        public ActionResult Edit()
        {

            return View();
        }
        public ActionResult CreateRoute()
        {
            ViewBag.BusOperatorList = new SelectList(context.BusOperators, "Id", "Name");
            ViewBag.LocationList = new SelectList(context.Locations, "Id", "Location");
            ViewBag.ExistingRouteList = new SelectList(context.Routes, "Id", "RouteName");
            return View("AddRouteView");
        }

        public ActionResult AddRouteView(RouteView routeView)
        {
            ViewBag.BusOperatorList = new SelectList(context.BusOperators, "Id", "Name");
            ViewBag.LocationList = new SelectList(context.Locations, "Id", "Location");
            ViewBag.ExistingRouteList = new SelectList(context.Routes, "Id", "RouteName");

            if (routeView.RouteId.HasValue)
            {
                #region for selected existing route
                OperatorRouteMap op = new OperatorRouteMap
                {
                    RouteId = routeView.RouteId.Value,
                    BusOperatorId = routeView.BusOperatorId
                };
                response= orm.Save(op);
                #endregion
            }
            else
            {
                #region New Route Adding
                List<string> Routes = new List<string>();
                var FromLocation = ls.GetById(routeView.From);
                Routes.Add(FromLocation.Location);

                if (routeView.Via!=null)
                {
                    foreach (var item in routeView.Via)
                    {
                        var ViaLocation = ls.GetById(item);
                        Routes.Add(ViaLocation.Location);
                    }
                }

                var ToLocation = ls.GetById(routeView.To);
                Routes.Add(ToLocation.Location);

                var name = string.Join("-", Routes);
                Route r = new Route()
                {
                    RouteName = name.ToString()
                };
                rs.Save(r);
                #region IsReverse is true
                if (routeView.IsReverse == true)
                {
                   Routes.Reverse();
                    var nameReverse = string.Join("-", Routes);
                    Route rr = new Route()
                    {
                        RouteName = nameReverse.ToString(),
                        ReverseId = r.Id
                    };
                    rs.Save(rr);

                    OperatorRouteMap opReverse = new OperatorRouteMap
                    {
                        RouteId = rr.Id,
                        BusOperatorId = routeView.BusOperatorId
                    };
                    orm.Save(opReverse);
                    int k = 1;
                    rps.Save(new RoutePoints() { RouteId = rr.Id, LocationId = routeView.To, SequenceId = k, IsFrom = true });
                    if (routeView.Via != null)
                    {
                        foreach (var item in routeView.Via.Reverse<int>())
                        {
                            k++;
                            rps.Save(new RoutePoints() { RouteId = rr.Id, LocationId = (int)item, SequenceId = k });
                        }
                    }

                    rps.Save(new RoutePoints() { RouteId = rr.Id, LocationId = routeView.From, SequenceId = ++k, IsTo = true });
                }
                #endregion
                OperatorRouteMap op = new OperatorRouteMap
                {
                    RouteId = r.Id,
                    BusOperatorId = routeView.BusOperatorId
                };
                response= orm.Save(op);

                int j = 1;
                rps.Save(new RoutePoints() { RouteId = r.Id, LocationId = routeView.From, SequenceId = j, IsFrom = true });

                if (routeView.Via != null)
                {
                    foreach (var item in routeView.Via)
                    {
                        j++;
                        rps.Save(new RoutePoints() { RouteId = r.Id, LocationId = (int)item, SequenceId = j });
                    }
                }

                rps.Save(new RoutePoints() { RouteId = r.Id, LocationId = routeView.To, SequenceId = ++j, IsTo = true });
                #endregion
            }
            
            switch (response.Success)
            {
                case true:
                    ViewBag.Message = successMessage;
                    break;

                case false:
                    ViewBag.Message = failureMessage;
                    break;
            }

            return View();
        }
   }
}

OnlineBusTicketManagement/OnlineBusTicketManagement/Views/Route/AddRouteView.cshtml
@model OBTM.Core.Models.RouteView

@{
    ViewBag.Title = "AddRouteView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-2">
        @Html.Partial("NavbarPartial")
    </div>
    <div class="col-md-10">


        @using (Html.BeginForm("AddRouteView", "Route", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h3>Route Add</h3>
            <hr />
            @if (ViewBag.Message != null)
            {
                <div class="alert alert-success alert-dismissible">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>@ViewBag.Message</strong>
                </div>
            }
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">

                @Html.Label("Bus Name:", htmlAttributes: new { @class = "control-Label col-md-2 " })
                <div class="col-md-3">
                    @Html.DropDownListFor(m => m.BusOperatorId, (SelectList)ViewBag.BusOperatorList, "--Select a bus operator--", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BusOperatorId, "", new { @class = "text-danger" })
                </div>
            </div>
            @*<div class="form-group">
            @Html.Label("Existing Route:", htmlAttributes: new { @class = "control-Label col-md-2" })

            <div class="col-md-3">
                @Html.DropDownListFor(m => m.Routes.Id, (SelectList)ViewBag.ExistingRouteList, "--Select a Location--", new { @class = "form-control", value = "0" })
            </div>
            <div class="col-md-2">
                <button type="button" class="btn btn-info active" id="btnAdd">Add</button>
            </div>
        </div>*@
            <div class="form-group">
                @Html.Label("Existing Route:", htmlAttributes: new { @class = "control-Label col-md-2" })
                @*<label for="ExistingRoutes">Existing Routes</label>*@
                <div class="col-md-3">
                    @Html.DropDownListFor(m => m.RouteId, (SelectList)ViewBag.ExistingRouteList, "--Select a Location--", new { @class = "form-control" })
                </div>
                <div class="col-md-2">
                    <button type="button" class="btn btn-primary active" id="btnAdd">Add</button>
                </div>
            </div>
            <div class="well" id="welll">
                <div class="form-group">
                    @Html.Label("From Location:", htmlAttributes: new { @class = "control-Label col-md-2 " })
                    @*<label for="LocationId">From</label>*@
                    <div class="col-md-3">
                        @Html.DropDownListFor(m => m.From, (SelectList)ViewBag.LocationList, "--Select a Location--", new { @class = "form-control" })
                        @*@Html.ValidationMessageFor(model => model.From, "", new { @class = "text-danger" })*@
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("Via Locations:", htmlAttributes: new { @class = "control-Label col-md-2 " })
                    @*<label for="LocationId">Via</label>*@
                    <div class="col-md-3">
                        @Html.ListBoxFor(m => m.Via, (SelectList)ViewBag.LocationList, new { @class = "ui fluid dropdown" })
                        @*@Html.ValidationMessageFor(model => model.Via, "", new { @class = "text-danger" })*@
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("To Location:", htmlAttributes: new { @class = "control-Label col-md-2 " })
                    @*<label for="LocationId">To</label>*@
                    <div class="col-md-3">
                        @Html.DropDownListFor(m => m.To, (SelectList)ViewBag.LocationList, "--Select a Location--", new { @class = "form-control" })
                        @*@Html.ValidationMessageFor(model => model.To, "", new { @class = "text-danger" })*@
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Is this route reversed?", htmlAttributes: new { @class = "control-Label col-md-2 " })
                    @*<label for="LocationId">To</label>*@
                    <div class="col-md-3">
                        @Html.CheckBoxFor(m => m.IsReverse)

                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" id="abc" class="btn btn-primary" />
                </div>
            </div>
        </div>
        }




        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

    </div>
</div>

@section scripts{
    <script data-require="jquery@2.2.4" data-semver="2.2.4" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <link data-require="bootstrap@3.3.0" data-semver="3.3.0" rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" />
    <script data-require="bootstrap@3.3.0" data-semver="3.3.0" src="https://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" class="ui" href="http://semantic-ui.com/dist/semantic.min.css">
    <script src="http://semantic-ui.com/dist/semantic.min.js"></script>

    <link href="http://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/css/bootstrap-multiselect.css" rel="stylesheet" type="text/css" />
    <script src="http://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/js/bootstrap-multiselect.js" type="text/javascript"></script>



    <script type="text/javascript">
        $(document).ready(function () {
            $("#welll").hide();
            $('.ui.dropdown').dropdown();
            $("#btnAdd").click(function () {
                //alert("button"); // Remove this line if it worked
               // $("#drpdwn")[0].selectedIndex = 0;
                $("#welll").show();
                //$("#abc").hide();

            });
        });

    </script>
}

OnlineBusTicketManagement/OnlineBusTicketManagement/Views/Route/Index.cshtml
@model IEnumerable<OBTM.Core.Models.BusOperator>

@{
    ViewBag.Title = "ViewRoute";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="row">

    <div class="col-md-2">
        @Html.Partial("NavbarPartial")
    </div>
    <div class="col-md-10">
        <h3>View Routes</h3>
        <input type="button" class="btn btn-primary" value="Create New" onclick="location.href='@Url.Action("CreateRoute", "Route")'" />
        <table class="table" id="">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Email)
                    </th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>

                        <td>
                            @foreach (var itm in item.OperatorRouteMaps)
                            {
                                <table>
                                    @if (itm.IsDeleted == null || itm.IsDeleted == false)
                                    {
                                        <tr>
                                            <td>@itm.Route.RouteName</td>
                                            <td>
                                                @Html.ActionLink("Delete", "Delete", new { id = itm.Id })
                                            </td>
                                        </tr>

                                    }
                                </table>
                            }


                        </td>
                    </tr>
                }
            </tbody>



        </table>
        <div class="pagination-container" style="text-align:center">
            <nav>
                <ul class="pagination"></ul>
            </nav>
        </div>

    </div>
</div>


@*@section scripts{
    <script>

        var table = '#OmyTable';

        $('.pagination').html('');
        var trnum = 0;
        var maxRows = 5;
        var totalRows = $(table + 'tbody tr').length;
        $(table + ' tr:gt(0)').each(function () {
            trnum++
            if (trnum > maxRows) {
                $(this).hide()
            }
            if (trnum <= maxRows) {
                $(this).show()
            }
        });
        if (totalRows > maxRows) {
            var pagenum = Math.ceil(totalRows / maxRows)
            for (var i = 1; i <= pagenum;) {
                $('.pagination').append('<li data-page="' + i + '">\<span>' + i++ + '<span class="sr-only">(current)</span></span>\</li>').show()
            }
        }
        $('.pagination li:first-child').addClass('active');
        $('.pagination li').on('click', function () {
            var pageNum = $(this).attr('data-page')
            var trIndex = 0;
            $('.pagination li').removeClass('active');
            $(this).addClass('active')
            $(table + ' tr:gt(0)').each(function () {
                trIndex++
                if (trIndex > (maxRows * pageNum) || trIndex <= ((maxRows * pageNum) - maxRows)) {
                    $(this).hide()
                } else {
                    $(this).show()
                }
            });
        });



    </script>
    }*@

OnlineBusTicketManagement/OnlineBusTicketManagement/Views/Route/ViewRoute.cshtml
@model IEnumerable<OBTM.Core.Models.BusOperator>

@{
    ViewBag.Title = "ViewRoute";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ViewRoute</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>

        <td>
            @foreach (var itm in item.OperatorRouteMaps)
            {
                if (itm.IsDeleted == null || itm.IsDeleted == false)
                {
        
                            @itm.Route.RouteName

                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                            @Html.ActionLink("Delete", "Delete", new { id = itm.Id })
               
                }

            }
           
    </tr>
}

</table>