OnlineBusTicketManagement/OnlineBusTicketManagement/Controllers/BusOperatorController.cs
using OBTM.Core.Models;
using OBTM.Service;
using OnlineBusTicketManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineBusTicketManagement.Controllers
{
    [AuthorizeWithSession]
    public class BusOperatorController : Controller
    {
        // GET: BusOperator
        BusOperatorService bo = new BusOperatorService();
        OperatorRouteMapService orms = new OperatorRouteMapService();
        public ActionResult Index()
        {
            var preBusList = bo.GetAllBusOperators();
            List<BusOperator> postBusList = new List<BusOperator>();
            foreach (var item in preBusList)
            {
                if (item.IsDeleted == null || item.IsDeleted == false)
                {
                    postBusList.Add(item);
                }
            }
            return View(postBusList);
        }
        public ActionResult SaveBusOperator(BusOperator model)
        {
            var id = model.Id;
            if (model.Id==0)
            {
                
                BusOperator b = new BusOperator()
                {
                    Name = model.Name,
                    Email = model.Email
                };
                bo.Save(b);
            }

            else
            {
                //bo.SaveEditedBus(model);
                bo.Update(model);
            }
            return RedirectToAction("Index");
        }
        public ActionResult CreateBusOperator()
        {
            BusOperator b = new BusOperator();
            return View("CreateEditBus", b);
        }
        public ActionResult Edit(int id)
        {
            
            
            BusOperator b = new BusOperator();
            b= bo.GetById(id);
            return View("CreateEditBus", b);
        }

        public ActionResult Delete(int id)
        {
            
            bo.DeleteBusSoft(id);
            orms.DeleteOperatorRouteSoft(id);
            return RedirectToAction("Index");
        }

    }
}

OnlineBusTicketManagement/OnlineBusTicketManagement/Controllers/BusSearchController.cs
using OBTM.Core.Models;
using OBTM.DataAccess;
using OBTM.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace OnlineBusTicketManagement.Controllers
{
    public class BusSearchController : Controller
    {
        RoutePointsService rps = new RoutePointsService();
        TripBaseService tbs = new TripBaseService();
        DateWiseTripService dws = new DateWiseTripService();
        LocationsService ls = new LocationsService();
        BookingTicketService bts = new BookingTicketService();
        OBTMDbContext context = new OBTMDbContext();

        public List<TripBase> tripBases = new List<TripBase>();
        public List<DateWiseTrip> dateWiseTrips = new List<DateWiseTrip>();
        public List<DateWiseTrip> orderedDateWise = new List<DateWiseTrip>();
        public List<DateWiseTrip> NewDateWise = new List<DateWiseTrip>();
        public List<TripBase> tripBaseFilter = new List<TripBase>();
        public List<DateWiseTrip> dateWiseTripFilter = new List<DateWiseTrip>();
        // GET: BusSearch
        public List<BusOperator> busOperators = new List<BusOperator>();
        public List<int> availableSeat = new List<int>();

        OBTMDbContext dbContext = new OBTMDbContext();

        BusOperatorService operatorService = new BusOperatorService();
        TripBaseService tripBaseService = new TripBaseService();
        BookingTicketService bookingTicketService = new BookingTicketService();
        DateWiseTripService dateWiseTripService = new DateWiseTripService();
        SeatBaseService seatBaseService = new SeatBaseService();
        public ActionResult SearchBus()
        {
            ViewBag.BusOperatorList = new SelectList(context.BusOperators, "Id", "Name");
            ViewBag.LocationList = new SelectList(context.Locations, "Id", "Location");
           
            return View(new SearchBus());
        }
        public ActionResult ViewSeat(int? dateWiseTripId)
        {
            //var temp = new List<int>() { 5, 10, 25 };
            ViewBag.Fare = dateWiseTripService.GetById(dateWiseTripId).Fare;
             var BookingTickets= bookingTicketService.GetAll().Where(m =>m.DateWiseTripId==dateWiseTripId&& m.IsBooked != true && m.IsTempLocked != true && m.IsDeleted==false).Select(m=>m.SeatName).ToList();
            ViewBag.SeatNoList = seatBaseService.GetAll().Where(m => BookingTickets.Contains(m.SeatName)).Select(m => m.Id).ToList();
            ViewBag.SeatNameList = seatBaseService.GetAll().Select(m => m.SeatName).ToList();
            ViewBag.DateWiseTripId = dateWiseTripId;
            //ViewBag.SeatList = temp;
            return View();
        }
       // [HttpPost]
        public ActionResult SearchResult(SearchBus searchBus)
        {
            ViewBag.BusOperatorList = new SelectList(context.BusOperators, "Id", "Name");
            ViewBag.LocationList = new SelectList(context.Locations, "Id", "Location");
            
            //ViewBag.LocationList = context.Locations.ToList();
            var routeList = rps.GetRoute(searchBus.From, searchBus.To);
            var from = ls.GetById(searchBus.From);
            var to = ls.GetById(searchBus.To);
            foreach (var item in routeList)
            {
                if (tbs.GetTripByRouteId(item)!=null)
                {
                    tripBases.AddRange(tbs.GetTripByRouteId(item));
                }
             
                
            }
            //var orderedTripbase = tripBases.OrderBy(a => a.DepartureTime);
            foreach (var item in tripBases)
            {
                if (dws.GetDateWiseByTrip(item.Id, searchBus.DepartureDate) != null)
                {
                    dateWiseTrips.AddRange(dws.GetDateWiseByTrip(item.Id, searchBus.DepartureDate));
                    
                }
                    
            }
            foreach (var item in dateWiseTrips)
            {
                if (item.Date >= DateTime.Now.Date)
                {
                    if (item.Date == DateTime.Now.Date)
                    {
                        if (item.TripBase.DepartureTime.TimeOfDay > DateTime.Now.AddHours(2).TimeOfDay)
                        {
                            NewDateWise.Add(item);
                        }
                    }
                    else
                    {
                        NewDateWise.Add(item);
                    }
                }
                

                
            }
            orderedDateWise = NewDateWise.OrderBy(a => a.TripBase.DepartureTime.TimeOfDay).ToList();

            foreach (var item in orderedDateWise)
            {
                availableSeat.Add(bts.GetAvailableSeatByDateWise(item.Id));
            }

            
            SearchBus s = new SearchBus
            {
                GetDateWiseTrip = orderedDateWise,
                FromLocation=from.Location,
                ToLocation=to.Location,
                noOfAvailableSeat=availableSeat            
            };

            return View(s);
        }
        [HttpPost]
        public ActionResult ModifySearch(SearchBus modifySearch)
        {
            return RedirectToAction("SearchResult", modifySearch);
        }

        //[HttpPost]
        //public JsonResult FilterSearchByBus(int busID, int fromLoc, int toLoc, DateTime date)
        //{
        //    int busOperator = Convert.ToInt32(busID);
        //    int from = Convert.ToInt32(fromLoc);
        //    int to = Convert.ToInt32(toLoc);
        //    DateTime dateVal = Convert.ToDateTime(date);
        //    var routeList = rps.GetRoute(from, to);

        //    foreach (var item in routeList)
        //    {
        //        if (tbs.GetTripByRouteIdAndBus(item,busID) != null)
        //        {
        //            tripBaseFilter.AddRange(tbs.GetTripByRouteIdAndBus(item, busID));
        //        }


        //    }
        //    foreach (var item in tripBases)
        //    {
        //        if (dws.GetDateWiseByTrip(item.Id, dateVal) != null)
        //        {
        //            dateWiseTripFilter.AddRange(dws.GetDateWiseByTrip(item.Id, dateVal));

        //        }

        //    }
        //    return Json(dateWiseTripFilter, JsonRequestBehavior.AllowGet);
        //}

    }
}

OnlineBusTicketManagement/OnlineBusTicketManagement/Controllers/TicketController.cs
using OBTM.Core.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OBTM.DataAccess;
using OBTM.Service;

namespace OnlineBusTicketManagement.Controllers
{
    public class TicketController : Controller
    {
        BookingTicketService bookingTicketService = new BookingTicketService();
        TicketService ticketService = new TicketService();

        // GET: Ticket
        public ActionResult Index()
        {
            return View();
        }
      
        public ActionResult ShowTicketInfo(String seatList, int totalFare,int dateWiseTripId)
        {
            var seatNameList = seatList.Split(',').ToList();
            var bookingTickets = bookingTicketService.GetAll().Where(m => m.DateWiseTripId == dateWiseTripId && seatNameList.Contains(m.SeatName)).ToList();
            //string[] arr1 = new string[] { "A", "B", "C" };
            foreach (var item in bookingTickets)
            {
                item.IsTempLocked = true;
                bookingTicketService.Update(item);
            }
            ViewBag.booking = bookingTickets;
            Ticket ticket = new Ticket()
            {
                Seats = seatList,
                TotalFare = totalFare,
                TicketPIN = ticketService.RandomNumber().ToString(),
                //Bookings = bookingTickets,
                
            };
            TempData["DateWise"] = dateWiseTripId;
            return View(ticket);
        }
        

        public ActionResult TicketDetails_(Ticket ticket)
        {
            var id = ticket.Id;
            var bookingTickets = bookingTicketService.GetAll().Where(m => m.DateWiseTripId ==(int) TempData["DateWise"] && ticket.Seats.Contains(m.SeatName)).ToList();
            Ticket T = new Ticket()
            {
                Name=ticket.Name,
                CellNo = ticket.CellNo,
                Email = ticket.Email,
                Seats=ticket.Seats,
                TotalFare = ticket.TotalFare,
                TicketPIN = ticket.TicketPIN,
                CreditCard = ticket.CreditCard
            };  
            ticketService.Save(T);

            foreach (var item in bookingTickets)
            {
                item.IsTempLocked = false;
                item.IsBooked = true;
                item.TicketId = T.Id;
                item.TicketPIN = ticket.TicketPIN;
                bookingTicketService.Update(item);
            }
            ticketService.SendEmail(ticket);
            return View(T);
        }

        public ActionResult CancelTicketView()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CancelTicketConfirm(Ticket ticket)
        {
            var cancel = bookingTicketService.GetAll().Where(i => i.TicketPIN == ticket.TicketPIN).FirstOrDefault();
            return View(cancel);
        }
        [HttpPost]
        public ActionResult CancelTicketDone(int id)
        {

            ticketService.DeleteSoft(id);
            ticketService.UpdateBooking(id);
            return RedirectToAction("SearchBus","busSearch");
        }
    }
}

OnlineBusTicketManagement/OnlineBusTicketManagement/Controllers/TripBaseController.cs
using OBTM.Core.Models;
using OBTM.Service;
using OnlineBusTicketManagement.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization.Json;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace OnlineBusTicketManagement.Controllers
{

    [AuthorizeWithSession]
    public class TripBaseController : Controller
    {
        TripBaseService tripBaseService = new TripBaseService();
        BusOperatorService busOperatorService = new BusOperatorService();
        RouteService routeService = new RouteService();
        OperatorRouteMapService operatorRouteMapService = new OperatorRouteMapService();

        // GET: TripBase
        public ActionResult Index(int operatorId=0, int routeId=0)
        {
            TripBase trip = new TripBase() { BusOperatorId = operatorId , RouteId = routeId };
            ViewBag.BusOperatorList = new SelectList(busOperatorService.GetAll().Where(m => m.IsDeleted != true).ToList(), "Id", "Name");
            ViewBag.ActionStatus = TempData["Status"];
            ViewBag.Massage = TempData["Massage"];
            return View(trip);
        }

        [HttpGet]
        public JsonResult GetBusRoute(int operatorId)
        {
            var routesIdList = operatorRouteMapService.GetAll().Where(m => m.IsDeleted != true && m.BusOperatorId == operatorId).Select(m => new { m.Route.Id, m.Route.RouteName }).ToList();
            return Json(routesIdList, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetBusTrips(int operatorId, int routeId)
        {
            IEnumerable<TripBase> tripList = tripBaseService.GetRefinedTrips(routeId, operatorId);
            ViewBag.BusOperatorId = operatorId;
            ViewBag.RouteId = routeId;
            return PartialView("TripPartial", tripList);
        }


        public ActionResult CreateTrip(int operatorId=0, int routeId=0)
        {
            ViewBag.BusOperatorList = new SelectList(busOperatorService.GetAll().Where(m => m.IsDeleted != true).ToList(), "Id", "Name");
            TripBase temp = new TripBase() { BusOperatorId = operatorId, RouteId = routeId };
            return View("TripInfo", temp);
        }


        [HttpPost]
        public ActionResult Create(TripBase trip)
        {
            bool actionStatus = false;
            if (ModelState.IsValid)
            {
                if (trip.Id == 0)
                {
                    actionStatus = tripBaseService.Save(trip).Success;
                    TempData["Status"] = actionStatus;
                    if (actionStatus == true)
                        TempData["Massage"] = "Successfully Created";
                    else
                        TempData["Massage"] = "Not Created";
                }

                else
                {
                    actionStatus = tripBaseService.Update(trip).Success;
                    TempData["Status"] = actionStatus;
                    if (actionStatus == true)
                        TempData["Massage"] = "Successfully Upadated";
                    else
                        TempData["Massage"] = "Not Updated";
                }
            }
            else
            {
                TempData["Status"] = actionStatus;
                TempData["Massage"] = "Wrong Input";

            }
            return RedirectToAction("Index",new { operatorId=trip.BusOperatorId, routeId=trip.RouteId});
        }

        public ActionResult Edit(int tripId)
        {
            ViewBag.BusOperatorList = new SelectList(busOperatorService.GetAll().Where(m => m.IsDeleted != true).ToList(), "Id", "Name");
            return View("TripInfo", tripBaseService.GetById(tripId));
        }

        public ActionResult Delete(int tripId)
        {
            var actionStatus = tripBaseService.Delete(tripId).Success;
            TempData["Status"] = actionStatus;
            if (actionStatus == true)
                TempData["Massage"] = "Successfully Deleted";
            else
                TempData["Massage"] = "Not Deleted";
            TripBase trip = tripBaseService.GetById(tripId);
            return RedirectToAction("Index", new { operatorId = trip.BusOperatorId, routeId = trip.RouteId});
        }

    }
}

OnlineBusTicketManagement/OnlineBusTicketManagement/Views/Shared/NavBarForUserEnd.cshtml
<!DOCTYPE html>
<html>
<head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <style>
        .nav-sidebar {
            width: 100%;
            padding: 8px 0;
            border-right: 1px solid #ddd;
        }

            .nav-sidebar a {
                color: #333;
                -webkit-transition: all 0.08s linear;
                -moz-transition: all 0.08s linear;
                -o-transition: all 0.08s linear;
                transition: all 0.08s linear;
                -webkit-border-radius: 4px 0 0 4px;
                -moz-border-radius: 4px 0 0 4px;
                border-radius: 4px 0 0 4px;
            }

            .nav-sidebar .active a {
                cursor: default;
                background-color: #428bca;
                color: #fff;
                text-shadow: 1px 1px 1px #666;
            }

                .nav-sidebar .active a:hover {
                    background-color: #428bca;
                }

            .nav-sidebar .text-overflow a,
            .nav-sidebar .text-overflow .media-body {
                white-space: nowrap;
                overflow: hidden;
                -o-text-overflow: ellipsis;
                text-overflow: ellipsis;
            }
    </style>
</head>
<body>
        <div class="col-sm-2">
            <nav class="nav-sidebar">
                <ul class="nav">
                    <li>@Html.ActionLink("User LogIn", "Index", "User")</li>
                    <li>@Html.ActionLink("Cancel Ticket", "CancelTicketView", "Ticket")</li>

                </ul>
            </nav>
        </div>

</body>
</html>

OnlineBusTicketManagement/OnlineBusTicketManagement/Views/Shared/NavbarPartial.cshtml

<!DOCTYPE html>
<html>
<head>

    <style>
        .vl {
            border-left: 1px solid #808080;
            height: 500px;
            position: absolute;
            left: 60%;
            margin-left: -3px;
            top: 0;
            
        }

        .nav-sidebar {
            width: 100%;
            min-height: 70vh;
            padding: 8px 0;
            border-right: 1px solid #ddd;
            
        }

            .nav-sidebar a {
                color: #333;
                -webkit-transition: all 0.08s linear;
                -moz-transition: all 0.08s linear;
                -o-transition: all 0.08s linear;
                transition: all 0.08s linear;
                -webkit-border-radius: 4px 4px 4px 4px;
                -moz-border-radius: 4px 0 0 4px;
                background-color: #2dcf74;
                border: 1px solid #338221;
            }
           
            .nav-sidebar .active a {
                cursor: default;
                background-color: #428bca;
                color: #fff;
                text-shadow: 1px 1px 1px #666;
            }

                .nav-sidebar .active a:hover {
                    background-color: #428bca;
                }

            .nav-sidebar .text-overflow a,
            .nav-sidebar .text-overflow .media-body {
                white-space: nowrap;
                overflow: hidden;
                -o-text-overflow: ellipsis;
                text-overflow: ellipsis;
            }

    </style>
</head>
<body>

    <nav class="nav-sidebar">
        <ul class="nav">
            @if (HttpContext.Current.Session["User"] != null)
            {
               <li>
                    <a href="#" id="btn-1" data-toggle="collapse" data-target="#submenu1" aria-expanded="false">Logged In as (@HttpContext.Current.Session["User"])</a>
                    <ul class="nav collapse" id="submenu1" role="menu" aria-labelledby="btn-1">
                        <li id="toggle">@Html.ActionLink("Log Out", "LogOut", "User")</li>

                    </ul>
                </li>
            }

            <li>@Html.ActionLink("Bus Operator", "Index", "BusOperator")</li>
            <li>@Html.ActionLink("Route", "Index", "Route")</li>
            <li>
                <a href="#" id="btn-2" data-toggle="collapse" data-target="#submenu2" aria-expanded="false">Trip</a>
                <ul class="nav collapse" id="submenu2" role="menu" aria-labelledby="btn-2">
                    <li>@Html.ActionLink("Search Trip", "Index", "TripBase")</li>
                    <li>@Html.ActionLink("Create Trip", "CreateTrip", "TripBase")</li>

                </ul>
            </li>
            <li>@Html.ActionLink("Datewise Trip", "Index", "DateWiseTrip")</li>
            <li>@Html.ActionLink("Admin", "ViewUsers", "User")</li>
        </ul>

    </nav>
    @*<div class="vl"></div>*@
</body>
</html>

OnlineBusTicketManagement/OnlineBusTicketManagement/Views/Shared/UserLayout.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - OnlineBusTicket.com</title>
    @Styles.Render("~/Content/css")
    
    

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <link rel="stylesheet" href="~/Content/footer-distributed-with-address-and-phones.css">
    <link rel="stylesheet" href="~/Content/demo.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">

    <style>
        .footer {
            background-color: #555;
            color: white;
            text-align: center;
            height: 80px
        }
        .required:after {
            content: "*";
            font-weight: bold;
            color: red;
            font-size:large;
        }
    </style>

    <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body class="container">

    <div class="row rounded" style="background-color:#088b42">
        <div class="col-md-2">
            <a href="@Url.Action("SearchBus","BusSearch")"><img src="~/Content/Picture/images.png" class="img-circle" alt="Cinque Terre" width="100" height="100"></a>
        </div>
        <div class="col-md-10" style="padding:30px 100px 0px 0px">
            <h2 style="color:white; text-align:center;">Online Bus Ticket</h2>
        </div>
    </div>
    <div class="row rounded">
        <nav class="navbar navbar-light" style="background-color: #2dcf74;  margin:0;">
            <div class="container-fluid navbar-right">

                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "SearchBus", "BusSearch")</li>
                    <li>@Html.ActionLink("Cancel Ticket", "CancelTicketView", "Ticket")</li>
                </ul>
            </div>

        </nav>
    </div>

    <div class="row" style="min-height:70vh;">
        @RenderBody()
    </div>
    <div class="row" style="">
        <footer class="footer-distributed" style=" background-color: #088b42;">
            <div class="footer-left">
                <h4>Company<span>logo</span></h4>
                <p class="footer-links">
                    @Html.ActionLink("Home", "SearchBus", "BusSearch")
                    ·
                    <a target="_blank" href="http://www.datagridbd.com">About</a>
                    ·
                    <a target="_blank" href="http://www.datagridbd.com/faqs/">FAQ</a>
                    ·
                    <a target="_blank" href="http://www.datagridbd.com/contact-us/">Contact Us</a>
                </p>
                <p class="footer-company-name">Datagrid Ltd. &copy; 2015</p>
            </div>
            <div class="footer-center">
                <div>
                    <i class="fa fa-map-marker"></i>
                    <p><span>Road# 19, House# 04, Sector# 11</span> Uttara, Dhaka</p>
                </div>
                <div>
                    <i class="fa fa-phone"></i>
                    <p>+88 02 58950905</p>
                </div>
                <div>
                    <i class="fa fa-envelope"></i>
                    <p>Email: info@datagridbd.com</p>
                </div>
            </div>
            <div class="footer-right">
                <p class="footer-company-about">
                    <h3>Follow Us</h3>
                </p>
                <div class="footer-icons">
                    <a target="_blank" href="https://www.facebook.com/Data-Grid-Limited-111397755610200/"><i class="fa fa-facebook"></i></a>
                    <a target="_blank" href="https://twitter.com/datagridlimited"><i class="fa fa-twitter"></i></a>
                    <a target="_blank" href="https://www.linkedin.com/company/data-grid-limited/"><i class="fa fa-linkedin"></i></a>
                    @*<a href="#"><i class="fa fa-github"></i></a>*@
                </div>
            </div>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/paginationScript.js")
    @RenderSection("scripts", required: false)


</body>
</html>

OnlineBusTicketManagement/OnlineBusTicketManagement/Views/Shared/_Layout.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - OnlineBusTicket.com</title>
    @Styles.Render("~/Content/css")
    

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <link rel="stylesheet" href="~/Content/footer-distributed-with-address-and-phones.css">
    <link rel="stylesheet" href="~/Content/demo.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">

    <style>
        .footer {
            background-color: #555;
            color: white;
            text-align: center;
            height: 80px
        }
        .required:after {
            content: "*";
            font-weight: bold;
            color: red;
            font-size: large;
        }
    </style>


</head>
<body class="container">

    <div class="row rounded" style="background-color:#088b42">
        <div class="col-md-2">
            <a href="@Url.Action("SearchBus","BusSearch")"><img src="~/Content/Picture/images.png" class="img-circle" alt="Cinque Terre" width="100" height="100"></a>
        </div>
        <div class="col-md-10" style="padding:30px 100px 0px 0px">
            <h2 style="color:white; text-align:center;">Online Bus Ticket</h2>
        </div>
    </div>

    <div class="row" style="min-height:70vh;">
        @RenderBody()
    </div>
    <div class="row" style="">
        <footer class="footer-distributed" style=" background-color: #088b42;">
            <div class="footer-left">
                <h4>Company<span>logo</span></h4>
                <p class="footer-links">
                    @Html.ActionLink("Home", "SearchBus", "BusSearch")
                    ·
                    <a target="_blank" href="http://www.datagridbd.com">About</a>
                    ·
                    <a target="_blank" href="http://www.datagridbd.com/faqs/">FAQ</a>
                    ·
                    <a target="_blank" href="http://www.datagridbd.com/contact-us/">Contact Us</a>
                </p>
                <p class="footer-company-name">Datagrid Ltd. &copy; 2015</p>
            </div>
            <div class="footer-center">
                <div>
                    <i class="fa fa-map-marker"></i>
                    <p><span>Road# 19, House# 04, Sector# 11</span> Uttara, Dhaka</p>
                </div>
                <div>
                    <i class="fa fa-phone"></i>
                    <p>+88 02 58950905</p>
                </div>
                <div>
                    <i class="fa fa-envelope"></i>
                    <p>Email: info@datagridbd.com</p>
                </div>
            </div>
            <div class="footer-right">
                <p class="footer-company-about">
                    <h3>Follow Us</h3>
                </p>
                <div class="footer-icons">
                    <a target="_blank" href="https://www.facebook.com/Data-Grid-Limited-111397755610200/"><i class="fa fa-facebook"></i></a>
                    <a target="_blank" href="https://twitter.com/datagridlimited"><i class="fa fa-twitter"></i></a>
                    <a target="_blank" href="https://www.linkedin.com/company/data-grid-limited/"><i class="fa fa-linkedin"></i></a>
                    @*<a href="#"><i class="fa fa-github"></i></a>*@
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @*<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>*@
    @Scripts.Render("~/Scripts/paginationScript.js")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
    @*@RenderSection("CreateDateWiseTripScript", required: false)*@

</body>
</html>